spring:
  application:
    name: map-struct-project

  datasource:
    url: jdbc:mysql://localhost:3306/mapstruct
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
     port: 8282   
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8383/eureka/
  instance:
    hostname: localhost     
