spring:
  application:
    name: map-struct-project

  datasource:
    url: jdbc:mysql://localhost:3306/mydb
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
     port: 8181   